# Generated by Django 5.2 on 2025-12-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_created_at_alter_expense_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
